version: '3'
services:
    mongo:
        container_name: mongodb
        image: mongo:3.6.2
        ports:
            - '27017:27017'
    mongo-seed:
        container_name: mongoseed
        build: ./db
        depends_on: 
            - mongo
    app:
        container_name: app
        restart: always
        build: .
        ports:
            - '3000:3000'
        depends_on:
            - mongo
